import sql from 'mssql';

export const sqlTypes = {
  bit: sql.Bit,
  bigInt: sql.BigInt,
  decimal: (precision, scale) => sql.Decimal(precision, scale),
  float: sql.Float,
  int: sql.Int,
  money: sql.Money,
  numeric: (precision, scale) => sql.Numeric(precision, scale),
  smallInt: sql.SmallInt,
  smallMoney: sql.SmallMoney,
  real: sql.Real,
  tinyInt: sql.TinyInt,
  char: (length) => sql.Char(length),
  nChar: (length) => sql.NChar(length),
  text: sql.Text,
  nText: sql.NText,
  varChar: length => sql.VarChar(length),
  nVarChar: length => sql.NVarChar(length),
  xml: sql.Xml,
  time: scale => sql.Time(scale),
  date: sql.Date,
  dateTime: sql.DateTime,
  dateTime2: scale => sql.DateTime2(scale),
  dateTimeOffset: scale => sql.DateTimeOffset(scale),
  smallDateTime: sql.SmallDateTime,
  uniqueIdentifier: sql.UniqueIdentifier,
  variant: sql.Variant,
  binary: sql.Binary,
  varBinary: length => sql.VarBinary(length),
  image: sql.Image,
  udt: sql.UDT,
  geography: sql.Geography,
  geometry: sql.Geometry,
};
